### ISSUE TITLE
The compressed package in the dataset folder cannot be extracted

### ISSUE THREAD

**Issue by upczl-zl** [meshmorphinggp/mmgp#1]
Hello, professor, can you provide the download address of the dataset, the file under the dataset folder in the code provided now does not seem to be a dataset.

**Comment by meshmorphinggp** [comment]
Hello, sorry for the late reply. I just tried to extract the dataset and it worked on my end. Can you provide an error message ?

**Comment by meshmorphinggp** [comment]
No update, re-open if needed
